
[functions.criar-manager]
enabled = true
verify_jwt = false
import_map = "./functions/criar-manager/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/criar-manager/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/criar-manager/*.html" ]

[functions.alterar-senha-manager]
enabled = true
verify_jwt = false
import_map = "./functions/alterar-senha-manager/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/alterar-senha-manager/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/alterar-senha-manager/*.html" ]
